// import { useState } from "react";
// import { generateID } from "Utilities/generateId";

// const [fields, setFields] = useState<Field[]>([
//     {
//       id: generateID(),
//       type: 'dropdown',
//       fieldLabel: 'Title',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 1,
//       label: 'title',
//       placeholder: 'select',
//       options: ['mr', 'mrs', 'pastor', 'herbalist'],
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Enter Surname',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: 'enter surname',
//       maxLength: 30,
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Enter FirstName',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: 'Enter First name',
//       maxLength: 30,
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Enter Other Names',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: 'Enter Other Names',
//       maxLength: 30,
//     },
//     {
//       id: generateID(),
//       type: 'date',
//       fieldLabel: 'Date of Birth',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: '',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Mothers Maiden Name ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: 'Enter Name ',
//       maxLength: 30,
//     },
//     {
//       id: generateID(),
//       type: 'dropdown',
//       fieldLabel: 'Gender ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: 'Select ',
//       options: ['male', 'female', 'others'],
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Residential Address',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: 'Enter Address ',
//       maxLength: 160,
//     },
//     {
//       id: generateID(),
//       type: 'dropdown',
//       fieldLabel: 'Marital Status ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: 'Select ',
//       options: ['single', 'married', 'complicated', 'divorced'],
//     },
//     {
//       id: generateID(),
//       type: 'textarea',
//       fieldLabel: 'Detailed Description of Address ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       placeholder: 'Enter Description ',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Mobile Number ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter Mobile Number',
//     },
//     {
//       id: generateID(),
//       type: 'dropdown',
//       fieldLabel: 'Means of Identification ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: 'Select ',
//       options: ['bvn', 'pvc', 'drivers license', 'nin'],
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Enter ID Number ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'ID Number',
//     },
//     {
//       id: generateID(),
//       type: 'date',
//       fieldLabel: 'ID issue date',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       placeholder: '',
//     },
//     {
//       id: generateID(),
//       type: 'date',
//       fieldLabel: 'ID expiry date',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       placeholder: '',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Biometric ID Number ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Biometric ID Number',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: ' Nationality ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter Nationality',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: ' State of Origin ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter State of Origin',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'LGA',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter LGA',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'City/Town',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter City/Town',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Occupation',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter Occupation',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Status/Job Title',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter Status/Job Title',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'Position/office of the officer',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter Position',
//     },
//     {
//       id: generateID(),
//       type: 'dropdown',
//       fieldLabel: 'Do you have dual citizenship ',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: false,
//       colSpan: 2,
//       label: 'surname',
//       placeholder: 'Select ',
//       options: ['yes', 'no'],
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: 'If yes, specify',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: '',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: ' Social Secret Number',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter SSN',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: ' Employee Identification Number',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter EIN',
//     },
//     {
//       id: generateID(),
//       type: 'textfield',
//       fieldLabel: ' Percentage Holding',
//       defaultValue: '',
//       value: '',
//       error: '',
//       required: true,
//       colSpan: 2,
//       placeholder: 'Enter Percentage Holding',
//     },
//   ])
