import { useState } from 'react'
import { generateID } from 'Utilities/generateId'
import { ExecutiveField } from '../Types/ExecutiveTypes'

export const ExecutiveDetailsInitial: ExecutiveField[] = [
  {
    id: generateID(),
    type: 'dropdown',
    fieldLabel: 'Title',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 1,
    placeholder: 'select',
    options: ['mr', 'mrs', 'pastor', 'herbalist'],
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Enter Surname',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 2,
    placeholder: 'enter surname',
    maxLength: 30,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Enter FirstName',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter First name',
    maxLength: 30,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Enter Other Names',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Other Names',
    maxLength: 30,
  },
  {
    id: generateID(),
    type: 'date',
    fieldLabel: 'Date of Birth',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: '',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: "Mother's Maiden Name",
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Name',
    maxLength: 30,
  },
  {
    id: generateID(),
    type: 'dropdown',
    fieldLabel: 'Gender',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Select ',
    options: ['male', 'female', 'others'],
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Residential Address',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Address',
    maxLength: 160,
  },
  {
    id: generateID(),
    type: 'dropdown',
    fieldLabel: 'Marital Status',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Select ',
    options: ['single', 'married', 'complicated', 'divorced'],
  },
  {
    id: generateID(),
    type: 'textarea',
    fieldLabel: 'Detailed Description of Address',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Description ',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Mobile Number',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Mobile Number',
  },
  {
    id: generateID(),
    type: 'dropdown',
    fieldLabel: 'Means of Identification',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Select ',
    options: ['bvn', 'pvc', 'drivers license', 'nin'],
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Enter ID Number',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'ID Number',
  },
  {
    id: generateID(),
    type: 'date',
    fieldLabel: 'ID Issue Date',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: '',
  },
  {
    id: generateID(),
    type: 'date',
    fieldLabel: 'ID Expiry Date',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: '',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Biometric ID Number',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Biometric ID Number',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Nationality',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Nationality',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'State of Origin',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter State of Origin',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'LGA',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter LGA',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'City/Town',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter City/Town',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Occupation',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Occupation',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Status/Job Title',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Status/Job Title',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Position/office of the officer',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Position',
  },
  {
    id: generateID(),
    type: 'dropdown',
    fieldLabel: 'Do you have Dual Citizenship',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Select ',
    options: ['yes', 'no'],
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'If yes, specify',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: '',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Social Secret Number',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter SSN',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Employee Identification Number',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter EIN',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Percentage Holding',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Percentage Holding',
  },
]
