export const SET_BULK_CREATION_SUMMARY = 'SET_BULK_CREATION_SUMMARY'

export const UPDATE_BULK_CUSTOMER_VALIDATION_PROFILE = 'UPDATE_BULK_CUSTOMER_VALIDATION_PROFILE'

export const VALIDATE_BULK_CUSTOMER_REQUEST = 'VALIDATE_BULK_CUSTOMER_REQUEST'
export const VALIDATE_BULK_CUSTOMER_SUCCESS = 'VALIDATE_BULK_CUSTOMER_SUCCESS'
export const VALIDATE_BULK_CUSTOMER_FAILED = 'VALIDATE_BULK_CUSTOMER_FAILED'