
export const GET_USER_ROLE_AND_PERMISSIONS_REQUEST = 'GET_USER_ROLE_AND_PERMISSIONS_REQUEST'
export const GET_USER_ROLE_AND_PERMISSIONS_SUCCESS = 'GET_USER_ROLE_AND_PERMISSIONS_SUCCESS'
export const GET_USER_ROLE_AND_PERMISSIONS_FAILED = 'GET_USER_ROLE_AND_PERMISSIONS_FAILED'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED'