import { SignatoryDetailsType } from '../Types/SignatoryTypes'

export const SignatoryDetailsInitial: SignatoryDetailsType = {
  Title: '',
  Surname: '',
  'First Name': '',
  'Other Names': '',
  "Mother's Maiden Name": '',
  'Date of Birth': '',
  'Marital Status': '',
  Gender: '',
  'Alternate Phone Number': '',
  'City/Town': '',
  'Detailed Description of Address': '',
  'Dual Citizenship': '',
  'Email address': '',
  'Employment Status': '',
  'ID Expiry Date': '',
  'ID Issue Date': '',
  'ID Number': '',
  'If yes, specify': '',
  'LGA-RA': '',
  'Means of Identification': '',
  'Mobile Number': '',
  'Nature of Business/Occupation': '',
  'P.O. Box': '',
  'Position/Rank': '',
  'Residential Address': '',
  'State of Origin': '',
  'Upload Passport Photograph': '',
  'Upload Proof of Address': '',
  'Upload Proof of Identity': '',
  Country: '',
  LGA: '',
  Nationality: '',
  State: '',
}

export interface SignatoryDetailsRequiredDataStatusType {
  [key: string]: 'required' | 'not required'
}

export const SignatoryDetailsRequiredDataStatus: SignatoryDetailsRequiredDataStatusType = {
  Title: 'required',
  Surname: 'required',
  'First Name': 'required',
  'Other Names': 'not required',
  "Mother's Maiden Name": 'not required',
  'Date of Birth': 'required',
  'Marital Status': 'required',
  Gender: 'required',
  'Alternate Phone Number': 'not required',
  'City/Town': 'required',
  'Detailed Description of Address': 'not required',
  'Dual Citizenship': 'required',
  'Email address': 'required',
  'Employment Status': 'required',
  'ID Expiry Date': 'not required',
  'ID Issue Date': 'not required',
  'ID Number': 'required',
  'If yes, specify': 'not required',
  'LGA-RA': 'required',
  'Means of Identification': 'required',
  'Mobile Number': 'required',
  'Nature of Business/Occupation': 'required',
  'P.O. Box': 'not required',
  'Position/Rank': 'not required',
  'Residential Address': 'required',
  'State of Origin': 'required',
  'Upload Passport Photograph': 'required',
  'Upload Proof of Address': 'required',
  'Upload Proof of Identity': 'required',
  Country: 'required',
  LGA: 'required',
  Nationality: 'required',
  State: 'required',
}
