import { SignatoryDetailsType, SignatoryInitialDetailsType } from '../Types/SignatoryTypes'

export const SignatoryDetailsInitial: SignatoryInitialDetailsType = {
  title: '',
  surname: '',
  firstName: '',
  otherNames: '',
  mothersMaidenName: '',
  dateOfBirth: '',
  maritalStatus: '',
  gender: '',
  alternatePhoneNumber: '',
  cityTown: '',
  detailedDescriptionOfAddress: '',
  dualCitizenship: '',
  emailAddress: '',
  employmentStatus: '',
  iDExpiryDate: '',
  iDIssueDate: '',
  iDNumber: '',
  ifYesSpecify: '',
  lGARA: '',
  meansOfIdentification: '',
  mobileNumber: '',
  natureOfBusinessOccupation: '',
  pOBox: '',
  positionRank: '',
  residentialAddress: '',
  stateOfOrigin: '',
  uploadPassportPhotograph: '',
  uploadProofOfAddress: '',
  uploadProofOfIdentity: '',
  country: '',
  lGA: '',
  nationality: '',
  state: '',
}

export interface SignatoryDetailsRequiredDataStatusType {
  [key: string]: 'required' | 'not required'
}

export const SignatoryDetailsRequiredDataStatus: SignatoryDetailsRequiredDataStatusType = {
  Title: 'required',
  Surname: 'required',
  'First Name': 'required',
  'Other Names': 'not required',
  "Mother's Maiden Name": 'not required',
  'Date of Birth': 'required',
  'Marital Status': 'required',
  Gender: 'required',
  'Alternate Phone Number': 'not required',
  'City/Town': 'required',
  'Detailed Description of Address': 'not required',
  'Dual Citizenship': 'required',
  'Email address': 'required',
  'Employment Status': 'required',
  'ID Expiry Date': 'not required',
  'ID Issue Date': 'not required',
  'ID Number': 'required',
  'If yes, specify': 'not required',
  'LGA-RA': 'required',
  'Means of Identification': 'required',
  'Mobile Number': 'required',
  'Nature of Business/Occupation': 'required',
  'P.O. Box': 'not required',
  'Position/Rank': 'not required',
  'Residential Address': 'required',
  'State of Origin': 'required',
  'Upload Passport Photograph': 'required',
  'Upload Proof of Address': 'required',
  'Upload Proof of Identity': 'required',
  Country: 'required',
  LGA: 'required',
  Nationality: 'required',
  State: 'required',
}
