import { SignatoryDetailsType } from '../Types/SignatoryTypes'

export const SignatoryDetailsInitial: SignatoryDetailsType = {
  Title: '',
  Surname: '',
  'First Name': '',
  'Other Names': '',
  "Mother's Maiden Name": '',
  'Date of Birth': '',
  'Marital Status': '',
  Gender: '',
  'Alternate Phone Number': '',
  'City/Town': '',
  'Detailed Description of Address': '',
  'Dual Citizenship': '',
  'Email address': '',
  'Employment Status': '',
  'ID Expiry Date': '',
  'ID Issue Date': '',
  'ID Number': '',
  'If yes, specify': '',
  'LGA-RA': '',
  'Means of Identification': '',
  'Mobile Number': '',
  'Nature of Business/Occupation': '',
  'P.O. Box': '',
  'Position/Rank': '',
  'Residential Address': '',
  'State of Origin': '',
  'Upload Passport Photograph': '',
  'Upload Proof of Address': '',
  'Upload Proof of Identity': '',
  Country: '',
  LGA: '',
  Nationality: '',
  State: '',
}
