// SEARCH

export const CUSTOMER_SEARCH_REQUEST = 'CUSTOMER_SEARCH_REQUEST'
export const CUSTOMER_SEARCH_SUCCESS = 'CUSTOMER_SEARCH_SUCCESS'
export const CUSTOMER_SEARCH_FAIL = 'CUSTOMER_SEARCH_FAIL'

export const GET_SINGLE_CUSTOMER_REQUEST = 'GET_SINGLE_CUSTOMER_REQUEST'
export const GET_SINGLE_CUSTOMER_SUCCESS = 'GET_SINGLE_CUSTOMER_SUCCESS'
export const GET_SINGLE_CUSTOMER_FAIL = 'GET_SINGLE_CUSTOMER_FAIL'
