export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST'
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS'
export const GET_CUSTOMERS_FAIL = 'GET_CUSTOMERS_FAIL'

export const GET_CUSTOMERS_ACTIVITY_LOG_REQUEST = 'GET_CUSTOMERS_ACTIVITY_LOG_REQUEST'
export const GET_CUSTOMERS_ACTIVITY_LOG_SUCCESS = 'GET_CUSTOMERS_ACTIVITY_LOG_SUCCESS'
export const GET_CUSTOMERS_ACTIVITY_LOG_FAIL = 'GET_CUSTOMERS_ACTIVITY_LOG_FAIL'

export const GET_REQUESTS_REQUEST = 'GET_REQUESTS_REQUEST'
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS'
export const GET_REQUESTS_FAIL = 'GET_REQUESTS_FAIL'

export const GET_REQUESTS_FOR_CHECKER_REQUEST = 'GET_REQUESTS_FOR_CHECKER_REQUEST'
export const GET_REQUESTS_FOR_CHECKER_SUCCESS = 'GET_REQUESTS_FOR_CHECKER_SUCCESS'
export const GET_REQUESTS_FOR_CHECKER_FAIL = 'GET_REQUESTS_FOR_CHECKER_FAIL'

export const DELETE_REQUEST_REQUEST = 'DELETE_REQUESTS_REQUEST'
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUESTS_SUCCESS'
export const DELETE_REQUEST_FAIL = 'DELETE_REQUESTS_FAIL'

export const ACTIVATE_CUSTOMER_REQUEST = 'ACTIVATE_CUSTOMER_REQUEST'
export const ACTIVATE_CUSTOMER_SUCCESS = 'ACTIVATE_CUSTOMER_SUCCESS'
export const ACTIVATE_CUSTOMER_FAIL = 'ACTIVATE_CUSTOMER_FAIL'

export const GET_CUSTOMERS_BY_DATE_REQUEST = 'GET_CUSTOMERS_BY_DATE_REQUEST'
export const GET_CUSTOMERS_BY_DATE_SUCCESS = 'GET_CUSTOMERS_BY_DATE_SUCCESS'
export const GET_CUSTOMERS_BY_DATE_FAIL = 'GET_CUSTOMERS_BY_DATE_FAIL'

export const GET_REQUESTS_BY_DATE_REQUEST = 'GET_REQUESTS_BY_DATE_REQUEST'
export const GET_REQUESTS_BY_DATE_SUCCESS = 'GET_REQUESTS_BY_DATE_SUCCESS'
export const GET_REQEUSTS_BY_DATE_FAIL = 'GET_REQEUSTS_BY_DATE_FAIL'

export const GET_TOTAL_REQUEST_STATUS_REQUEST = 'GET_TOTAL_REQUEST_STATUS_REQUEST'
export const GET_TOTAL_REQUEST_STATUS_SUCCESS = 'GET_TOTAL_REQUEST_STATUS_SUCCESS'
export const GET_TOTAL_REQUEST_STATUS_FAIL = 'GET_TOTAL_REQUEST_STATUS_FAIL'

export const GET_SINGLE_REQUEST_REQUEST = 'GET_SINGLE_REQUEST_REQUEST'
export const GET_SINGLE_REQUEST_SUCESS = 'GET_SINGLE_REQUEST_SUCESS'
export const GET_SINGLE_REQUEST_FAIL = 'GET_SINGLE_REQUEST_FAIL'

export const SET_REQUIRED_FORM_FIELDS = 'SET_REQUIRED_FORM_FIELDS'

export const UPDATE_REQUEST_REQUEST = 'UPDATE_REQUEST_REQUEST'
export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS'
export const UPDATE_REQUEST_FAIL = 'UPDATE_REQUEST_FAIL'

export const GET_CATEGORIZED_PRODUCTS_REQUEST = 'GET_CATEGORIZED_PRODUCTS_REQUEST'
export const GET_CATEGORIZED_PRODUCTS_SUCCESS = 'GET_CATEGORIZED_PRODUCTS_SUCCESS'
export const GET_CATEGORIZED_PRODUCTS_FAIL = 'GET_CATEGORIZED_PRODUCTS_FAIL'

export const GET_PRODUCTS_BY_CATEGORY_REQUEST = 'GET_PRODUCTS_BY_CATEGORY_REQUEST'
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'GET_PRODUCTS_BY_CATEGORY_SUCCESS'
export const GET_PRODUCTS_BY_CATEGORY_FAIL = 'GET_PRODUCTS_BY_CATEGORY_FAIL'


export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL'

export const GET_SINGLE_PRODUCT_REQUEST = 'GET_SINGLE_PRODUCT_REQUEST'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_FAIL = 'GET_SINGLE_PRODUCT_FAIL'




