export const CUSTOMER360_PRODUCT_REQUEST = 'CUSTOMER360_PRODUCT_REQUEST'
export const CUSTOMER360_PRODUCT_SUCCESS = 'CUSTOMER360_PRODUCT_SUCCESS'
export const CUSTOMER360_PRODUCT_FAILED = 'CUSTOMER360_PRODUCT_FAILED'
