export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST'
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS'
export const GET_CUSTOMERS_FAIL = 'GET_CUSTOMERS_FAIL'

export const GET_REQUESTS_REQUEST = 'GET_REQUESTS_REQUEST'
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS'
export const GET_REQUESTS_FAIL = 'GET_REQUESTS_FAIL'


export const SORT_CUSTOMERS_ALPHABETICALLY_REQUEST = 'SORT_CUSTOMERS_ALPHABETICALLY_REQUEST'
export const SORT_CUSTOMERS_ALPHABETICALLY_SUCCESS = 'SORT_CUSTOMERS_ALPHABETICALLY_SUCCESS'
export const SORT_CUSTOMERS_ALPHABETICALLY_FAIL = 'SORT_CUSTOMERS_ALPHABETICALLY_FAIL'


