export const CUSTOMER360_REWARDS_REQUEST = 'CUSTOMER360_REWARDS_REQUEST'
export const CUSTOMER360_REWARDS_SUCCESS = 'CUSTOMER360_REWARDS_SUCCESS'
export const CUSTOMER360_REWARDS_FAILED = 'CUSTOMER360_REWARDS_FAILED'
