export const GET_FORM_REQUEST = 'GET_FORM_REQUEST'
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS'
export const GET_FORM_FAIL = 'GET_FORM_FAIL'

export const GET_PUBLISHED_FORM_SECTION_REQUEST = 'GET_PUBLISHED_FORM_SECTION_REQUEST'
export const GET_PUBLISHED_FORM_SECTION_SUCCESS = 'GET_PUBLISHED_FORM_SECTION_SUCCESS'
export const GET_PUBLISHED_FORM_SECTION_FAIL = 'GET_PUBLISHED_FORM_SECTION_FAIL'
