export const GET_FORM_REQUEST = 'GET_FORM_REQUEST'
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS'
export const GET_FORM_FAIL = 'GET_FORM_FAIL'

export const GET_PUBLISHED_FORM_SECTION_REQUEST = 'GET_PUBLISHED_FORM_SECTION_REQUEST'
export const GET_PUBLISHED_FORM_SECTION_SUCCESS = 'GET_PUBLISHED_FORM_SECTION_SUCCESS'
export const GET_PUBLISHED_FORM_SECTION_FAIL = 'GET_PUBLISHED_FORM_SECTION_FAIL'

export const STATUS_FOR_CAN_PROCEED = 'STATUS_FOR_CANT_PROCEED'

export const SHOW_WAIVER_MODAL_IN_FORM = 'SHOW_WAIVER_MODAL_IN_FORM'

export const ACTIVE_PAGE = 'ACTIVE_PAGE'

export const UNFILLED_REQUIRED_SIGNATORY_LIST = 'UNFILLED_REQUIRED_SIGNATORY_LIST'
export const UNFILLED_REQUIRED_SIGNATORY_LIST_BUTTON = 'UNFILLED_REQUIRED_SIGNATORY_LIST_BUTTON'

export const SUBMIT_FORM_REQUEST = 'SUBMIT_FORM_REQUEST'
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS'
export const SUBMIT_FORM_FAIL = 'SUBMIT_FORM_FAIL'
