export const VALIDATE_CUSTOMER_REQUEST = 'VALIDATE_CUSTOMER_REQUEST'
export const VALIDATE_CUSTOMER_SUCCESS = 'VALIDATE_CUSTOMER_SUCCESS'
export const VALIDATE_CUSTOMER_FAIL = 'VALIDATE_CUSTOMER_FAIL'
export const VALIDATE_CUSTOMER_RESULT_MODAL = 'VALIDATE_CUSTOMER_RESULT_MODAL'
