import { useState } from 'react'
import { generateID } from 'Utilities/generateId'
import { ExecutiveField } from '../Types/ExecutiveTypes'

export const additionalDetailsInitial = (): ExecutiveField[] => [
  {
    id: generateID(),
    type: 'dropdown',
    fieldLabel: 'Title',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 1,
    placeholder: 'select',
    options: ['mr', 'mrs', 'pastor', 'herbalist'],
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Enter Surname',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 2,
    placeholder: 'enter surname',
    maxLength: 30,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Enter FirstName',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter First name',
    maxLength: 30,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Enter Other Names',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Other Names',
    maxLength: 30,
  },
  {
    id: generateID(),
    type: 'date',
    fieldLabel: 'Date of Birth',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: '',
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: "Mother's Maiden Name",
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Name',
    maxLength: 30,
  },
]
