import { generateID } from 'Utilities/generateId'
import { AdditionalDetailField } from '../Types/AdditionalTypes'

export const additionalDetailsInitial = (): AdditionalDetailField[] => [
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Bank/Branch Name',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 2,
    placeholder: 'Enter Bank Name',
    maxLength: 30,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Bank/Branch Address',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 2,
    placeholder: 'Enter Bank Address',
    maxLength: 160,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Account Name',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Account Name',
    maxLength: 160,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Account Number',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Account Number',
    maxLength: 160,
  },
  {
    id: generateID(),
    type: 'date',
    fieldLabel: 'Date of Creation',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: '',
  },
  {
    id: generateID(),
    type: 'dropdown',
    fieldLabel: 'Account Status',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 1,
    placeholder: 'Select',
    options: ['active', 'dormant'],
  },
]
