import { generateID } from 'Utilities/generateId'
import { AdditionalDetailField, AffiliatedCompanyDetailField } from '../Types/AdditionalTypes'

export const additionalDetailsInitial = (): AdditionalDetailField[] => [
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Bank/Branch Name',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 2,
    placeholder: 'Enter Bank Name',
    maxLength: 60,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Bank/Branch Address',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 2,
    placeholder: 'Enter Bank Address',
    maxLength: 160,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Account Name',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Account Name',
    maxLength: 90,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Account Number',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Enter Account Number',
    maxLength: 30,
  },
  {
    id: generateID(),
    type: 'date',
    fieldLabel: 'Date of Creation',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: '',
  },
  {
    id: generateID(),
    type: 'dropdown',
    fieldLabel: 'Account Status',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 1,
    placeholder: 'Select',
    options: ['Active', 'Dormant'],
  },
]
export const affiliatedCompanyDetailsInitial = (): AffiliatedCompanyDetailField[] => [
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Name of Company/Body 1',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 2,
    placeholder: 'Naza concept SA ltd',
    maxLength: 60,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Name of Company/Body 2',
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 2,
    placeholder: 'Naza concept SA ltd',
    maxLength: 160,
  },
  {
    id: generateID(),
    type: 'text',
    fieldLabel: 'Name of Company/Body 3',
    defaultValue: '',
    value: '',
    error: '',
    required: 'off',
    colSpan: 2,
    placeholder: 'Naza concept SA ltd',
    maxLength: 90,
  },
  {
    id: generateID(),
    type: 'dropdown',
    fieldLabel: "Parent Company's Country of Incorporation",
    defaultValue: '',
    value: '',
    error: '',
    required: 'on',
    colSpan: 1,
    placeholder: 'Select',
    options: ['Nigeria'],
  },
]
