#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn exec pretty-quick --staged && yarn exec concurrently yarn:test yarn:lint

# yarn exec concurrently yarn:format yarn:lint && yarn exec pretty-quick --staged
